---
- name: Include role. Ssh generator
  include_role:
    name: gudron.ssh_keys_generator
  vars: 
    new_keys: "{{ new_users_values | map(attribute='ssh.keys') | list | flatten }}"

- name: Include role. Create users
  include_role:
    name: gudron.os_users
  vars: 
    users_list_params: "{{ new_users_values }}"
    groups_list_params: "{{ new_groups_params }}"

- name: Include role. Ssh server
  include_role:
    name: gudron.ssh_server
  vars:
    ssh_port: "{{ ssh_params.bind_port }}"
    ssh_permit_root_login: "{{ ssh_params.permit_root_login }}"
    ssh_permit_empty_password: "{{ ssh_params.permit_empty_password }}"
    ssh_permit_password_authentication: "{{ ssh_params.permit_password_authentication }}"

